name: Cron Test
on:
  schedule:
    # 日本時間の 6/1 16:25 に実行
    - cron: '25 7 1 6 *'
    # 1h ごとに実行
    # - cron: '0 * * * *'

jobs:
  build:
    name: Hello World
    runs-on: ubuntu-18.04
    steps:
      - run: echo "Hello World!!"


